
// GlobalUsings.cs (API)
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Caching.Memory;
global using System.Text.Json;
global using GitHub.API.Models;
global using GitHub.API.Services;
global using GitHub.Infrastructure.Servicies;
global using Microsoft.AspNetCore.Authorization;
global using GitHub.Application.Abstractions;
global using GitHub.Application.Auth;
global using GitHub.Application.Dtos;
global using System.Security.Claims;
global using GitHub.Domain.Users;
global using GitHub.Infrastructure.Auth;
global using GitHub.Infrastructure.Repositories;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using GitHub.API.Middlewares;
global using Microsoft.OpenApi.Models;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using System.Text;
//global using GitHub.API.Models;
//global using GitHub.Application.Abstractions;
//global using GitHub.Application.Auth;
//global using GitHub.Application.Dtos;
//global using System.Security.Claims;
